sudo: true
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install gcc-4.9 g++-4.9 lcov;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20;
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 20;
  - sudo update-alternatives --config gcc;
  - sudo update-alternatives --config g++;
  - sudo update-alternatives --config gcov;
git:
  depth: 100
os:
  - linux
  - osx
