sudo: true
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6
  - sudo apt-get install build-essential
git:
  depth: 100
os:
  - linux
  - osx
