sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install gcc-4.9 g++-4.9 lcov;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20;
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 20;
  - sudo update-alternatives --config gcc;
  - sudo update-alternatives --config g++;
  - sudo update-alternatives --config gcov;
  - wget http://downloads.sourceforge.net/ltp/lcov-1.10.tar.gz;
  - tar xvfz lcov-1.10.tar.gz;
  - sudo cp -v lcov-1.10/bin/{lcov,genpng,gendesc,genhtml,geninfo} /usr/bin/;
  - sudo chmod 777 /usr/bin/lcov /usr/bin/genhtml /usr/bin/geninfo /usr/bin/genpng /usg/bin/gendesc;
  - rm -rf lcov-1.10.tar.gz lcov-1.10;
  - sudo mv -v `which gcov-4.8` `which gcov`;
  - export GYP_DEFINES="coverage=1";
  - export JOBS=4;
  - BUILD_ONLY=true npm install
git:
  depth: 1
os:
  - linux
  - osx
